#My miniaml tmux configuration file with some custom colors and plugins.
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-kitty:RGB"


set -g focus-events on
set -g allow-passthrough on


#general 
set -g set-clipboard on  # allows tmux to use the system clipboard
set -g mouse on   # enables mouse support for resizing panes, selecting windows, etc.
set -g history-limit 10000 # increase scrollback history-limit

set -g status-interval 3 # refresh status bar every 3 seconds
# set -g detach-on-destroy off # allows you to keep the tmux session running even if you close the terminal window

#key bindings
unbind C-b # unbind default prefix
set -g prefix C-a # set prefix to ctrl-space

#Refresh tmux config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# split panes using | and -
unbind %
bind | split-window -h -c "#{pane_current_path}" # split horizontally and start in the current directory

unbind \"
bind - split-window -v -c "#{pane_current_path}" # split vertically and start in the current directory

# New window in same path
bind c new-window -c "#{pane_current_path}"

# Alt + number to switch tabs (windows)
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Alt + s to switch sessions
bind -n M-s choose-session

# Alt + a to add new tab (window)
bind -n M-a new-window -c "#{pane_current_path}"

# Alt + c to close current tab (window)
bind -n M-k kill-window

# vim arrow to resize panes
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r m resize-pane -Z # toggle zoom for the current pane


# Enable vi mode to allow vim movements
set-window-option -g mode-keys vi

#Copy text with "y"
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "xclip -in -sel clip"

#select 
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection

#Dont exit copy mode when dragging mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

 #start window
  set -g base-index 1 # start window numbering at 1 instead of 0
  set -g pane-base-index 1 # start pane numbering at 1 instead of 0
  set -g renumber-windows on # renumber windows when one is closed

#List of plungins
set -g @plugin 'tmux-plugins/tpm' # tmux plugin manager

set -g @plugin 'christoomey/vim-tmux-navigator' # tmux and vim navigation
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions across system restarts
set -g @plugin 'tmux-plugins/tmux-continuum' # automatic tmux-plugins
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor' # cpu and memory monitor for tmux status bar

set -g @resurrect-capture-pane-contents 'off' 
set -g @continuum-restore 'on' # automatically restore tmux sessions when tmux is started
 set -g status-right " #{cpu -i 3} | 󰍛 #{mem} "
 set -g status-justify centre
 set -g status-left-length 200
 set -g status-right-length 200

#custom colors
bg='#3B4252'
default_fg='#D8DEE9'
session_fg='#A3BE8C'
session_selection_fg='3B4252'
session_selected_bg='#81A1C1'
active_window_fg='#88C0D0'
active_pane_border='#abb2bf'
inactive_window_fg='#4C566A'
inactive_pane_border='#4C566A'

set -g status-style "bg=${bg}"
set -g status-left "#[fg=${session_fg},bold,bg=${bg}]  #S "
set -g window-status-current-format "#[fg=${active_window_fg},bg=default]  #I:#W "
set -g window-status-format "#[fg=${default_fg},bg=default] #I:#W"
set -g window-status-last-style "fg=${default_fg},bg=default"

set -g pane-border-lines simple
set -g pane-active-border-style "fg=${active_pane_border},bg=default"
set -g pane-border-style fg=black,bright




# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

